apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "prometheus.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 9090
      targetPort: 9090
