apiVersion: v1
kind: Service
metadata:
  name: kb-worker
  labels:
    {{- include "kb-worker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "kb-worker.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 8002
      targetPort: 8002
