apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    chart: external-dns
    targetRevision: 1.15.0
    helm:
      releaseName: external-dns
      valuesObject:
        provider:
          name: aws
        serviceAccount:
          create: true
          name: external-dns
        policy: sync
        domainFilters:
        - lab.karansiddhu.com
        txtOwnerId: magoneai
        env:
        - name: AWS_REGION
          value: us-east-1
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 8
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
