apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:KaranSiddhu/testing-aws-magure-deploy.git
    targetRevision: main
    path: k8s/charts/redis
  destination:
    server: https://kubernetes.default.svc
    namespace: magoneai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 8
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    name: redis
    jsonPointers:
    - /spec/volumeClaimTemplates
