apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
  labels:
    {{- include "temporal-ui.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "temporal-ui.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
