apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  labels:
    {{- include "promtail.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "promtail.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "promtail.labels" . | nindent 8 }}
    spec:
      serviceAccountName: magoneai-app
      containers:
        - name: promtail
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - "-config.file=/etc/promtail/promtail.yml"
          ports:
            - name: http
              containerPort: 9080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: varlog
              mountPath: /var/log/pods
              readOnly: true
            - name: containers
              mountPath: /var/lib/containers
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: varlog
          hostPath:
            path: /var/log/pods
        - name: containers
          hostPath:
            path: /var/lib/containers
