apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-pdb
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
