apiVersion: v1
kind: Service
metadata:
  name: superadmin
  labels:
    {{- include "superadmin.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "superadmin.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 3000
      targetPort: 3000
