apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-pdb
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "web.selectorLabels" . | nindent 6 }}
