apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pgbouncer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pgbouncer.labels" . | nindent 8 }}
    spec:
      containers:
        - name: pgbouncer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: [pgbouncer, /etc/pgbouncer/pgbouncer.ini]
          ports:
            - containerPort: 6432
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          livenessProbe:
            tcpSocket:
              port: 6432
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 6432
            periodSeconds: 10
          volumeMounts:
            - name: pgbouncer-config
              mountPath: /etc/pgbouncer
              readOnly: true
      volumes:
        - name: pgbouncer-config
          secret:
            secretName: pgbouncer-config
